In [11]:
# chapter 1
# introduction to numpy

temperatures = [11.2,12.3,13.4,14.5,15.5]

total = 0

for temp in temperatures:
    total += temp

result = total/len(temperatures)
print(total)

66.9


In [3]:
!pip install numpy
# for vs code -  pip3 install numpy
# for google colab its pre-installed


In [2]:
import numpy as np

temperatures = np.array([11.2,12.3,13.4,14.5,15.5])
average = np.mean(temperatures)
print(average)

13.38


In [5]:
python_list = [1,2,3,4,5]
print(python_list)  # prints list with comma

import numpy as np
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)   # prints list without array

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [7]:
# one dimensional array

import numpy as np
arr_1d = np.array([10,20,30,40,50])

print(arr_1d)

[10 20 30 40 50]


In [9]:
# two dimensional array

import numpy as np
arr_2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# multi dimensional array

import numpy as np

matrix = np.array([[2,4,6],
                   [8,10,12]])
print(matrix)



[[ 2  4  6]
 [ 8 10 12]]


In [3]:
# creating arrays from python lists
# np.array([ele1, ele2, ele3])

import numpy as np

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [5]:
# with default values
# np.zeros(shape)  , (3) for 1d, (3,3) for 2d

import numpy as np
zeroes_array = np.zeros(3)
print(zeroes_array)


[0. 0. 0.]


In [6]:
# ones(shape)

import numpy as np

ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# full(shape, value)

import numpy as np

filled_Array = np.full((2,2),7)
print(filled_Array)

[[7 7]
 [7 7]]


In [8]:
# creating sequences of numbers in numpy
# arange()
# arange(start,stop,step)

import numpy as np

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [10]:
# creating identity matrices
# eye(size)

import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# chapter 2 
# Array Properties & Operations

import numpy as np

arr_2d = np.array([[1,2,3],
                   [4,5,6]])

print(arr_2d.shape)  # no of rows and columns
print(arr_2d.size)  # total no of elements
print(arr_2d.ndim)  # no of dimensions
print(arr_2d.dtype)  # datatype of elements
print(arr_2d.astype(str))  # changing datatype (int, float, str)



(2, 3)
6
2
int64
[['1' '2' '3']
 ['4' '5' '6']]


In [11]:
import numpy as np

arr = np.array([10,20,30])    # no need of loops 

print(arr + 5)
print(arr * 10)
print(arr ** 2)

[15 25 35]
[100 200 300]
[100 400 900]


In [14]:
# Aggregation function(summarize)

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

210
10.5
1
20
5.766281297335398
33.25


In [16]:
# chapter 3 - Indexing and slicing

# indexing - single element
# slicing - multiple element

# fancy indexing - using list of index
# boolean masking - giving condition and then filtering

import numpy as np

"""
array [index] #1d array
array [row, column] #2d array

"""
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[1])
print(arr[3])
print(arr[-1])







10
20
40
50


In [20]:
"""
slicing - start,stop-excluded,step-default-1
arr[start:stop:step]
arr[start:end], start to end -1
negative step, -1 reverse

"""
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[1:5])  # start to end -1
print(arr[:4])  # begining to end -1
print(arr[::2])  # pickes every second element
print(arr[::-1])  # reverse







[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [24]:
# fancy indexing - selecting multiple elements at once

import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[[0,2,4]])  # its a copy of original list, here original list is not changed



[10 30 50]


In [25]:
# boolean masking - filtering data using conditions

import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[arr > 25])


[30 40 50 60]


In [28]:
# Reshaping and manipulating array
# 1. reshaping - modifying dimension without modifying the data, like 1d to 2d or 3d. It can change rows and columns

"""
reshape(rows, columns) specify new shape
if dimensions match

"""

import numpy as np

arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)  # does not create copy of original list, it returns a view
print(reshaped_arr)



[[1 2 3]
 [4 5 6]]


In [3]:
# 2. flatten 
"""
.ravel() - return views
.flatten() - return copy

"""

import numpy as np

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
# chapter 4 - Reshaping and Mnipulating arrays

# 1. insert 
"""
np.insert(array, index, value, axis = None)
array - original array
index -
value -
axis - None, flatten
axis - 0, row-wise
axis - 1, column wise



"""

import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.insert(arr, 2, 100, axis = 0)
print(new_arr)



[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [11]:
# for 2 d array

import numpy as np

arr_2d = np.array([[1,2],[3,4]])
print(arr_2d)

# insert a new row at index 1
new_arr_2d = np.insert(arr_2d, 1, [5,6], axis = 0)
print(new_arr_2d)


[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]


In [15]:
# 2. append

import numpy as np

arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50,60])

print(new_arr)


[10 20 30 40 50 60]


In [16]:
# 3. concatenate

"""
np.concatenate((array1,array2), axis = 0)

axis 0 > vertical stacking
axis 1 > horizontal stacking

"""

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[1 2 3 4 5 6]


In [17]:
# 4. delete

"""

np.delete(array, index, axis = None)
flatten array

"""

import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.delete(arr, 2)
print(new_arr)


[10 20 30 40 50 60]
[10 20 40 50 60]


In [18]:
# delete for 2d array

import numpy as np

arr_2d = np.array([[1,2,3],[4,5,6]])

new_arr_2d = np.delete(arr_2d, 0, axis = 0)
print(new_arr_2d)


[[4 5 6]]


In [20]:
# stacking and splitting

# 1. stacking
"""
vertically
horizontally

vstack() row wise
hstack() column wise

"""
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr1, arr2))) # vertical stack
print(np.hstack((arr1, arr2))) # horizontal stack


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [23]:
# 2. splitting
"""

np.split()
equal

np.vsplit()
np.hsplit()

"""
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(np.split(arr, 2))   # 2 - size


[array([10, 20, 30]), array([40, 50, 60])]


In [45]:
# chapter 5 - broadcasting and vectorization

"""
broadcasting - expand small arrays to larger arrays, so they can match
faster than loops
use - 1d to 2d broadcasting

"""

prices = [100,200,300]
discount = 10   # 10% discount

final_prices = []

for price in prices:
    final_price = price - (price * discount/100)
    final_prices.append(final_price)

print(final_prices)



[90.0, 180.0, 270.0]


In [26]:
# loops in slow in large datasets
# broadcasting - without loop

import numpy as np

prices = np.array([100,200,300])
discount = 10

final_prices = prices - (prices * discount/100)
print(final_prices)


[ 90. 180. 270.]


In [31]:
# how numpy handle arrays of diff shapes
# rule 1 : matching dimension, eg:  [1,2,3] + [4,5,6] = [5,7,9]
# rule 2 : expanding single elements, eg: [1,2,3] + 10 = [11,12,13]
# rule 3 : incompatible shapes, eg: [1,2,3] + [5,6] = error

import numpy as np

arr = np.array([100,200,300])
result = arr * 2
print(result)

[200 400 600]


In [34]:
# 1d to 2d
import numpy as np

matrix = np.array([[1,2,3],[4,5,6]])  # 2*3 matrix
vector = np.array([10,20,30])  # 1d array

result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [38]:
# error

"""
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])  # shape(2,3)
arr2 = np.array([1,2])  # shape(2,)

result = arr1 + arr2
print(result)
"""

'\nimport numpy as np\n\narr1 = np.array([[1,2,3],[4,5,6]])  # shape(2,3)\narr2 = np.array([1,2])  # shape(2,)\n\nresult = arr1 + arr2\nprint(result)\n'

In [46]:
# vectorization - operations in all without using loops

"""
vectorization - entire array
100 times faster than loops
use - matrix operation
"""

list1 = [1,2,3]
list2 = [4,5,6]

result = [x+y for x,y in zip(list1, list2)]
print(result)



[5, 7, 9]


In [40]:
# using vectorization

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)

[5 7 9]


In [42]:
import numpy as np

arr = np.array([10,20,30])
multiplied = arr * 3

print(multiplied)


[30 60 90]


In [48]:
# chapter 6 - Handling Missing & Special Values

"""
like to solve divisible by zero error handling
have 3 built-in functions
1. np.isnan - detect missing values, nan - not a number
2. np.nan_to_num() 
3. np.isinf() - detect infinite values

"""
# 1. isnan - detect missing values

import numpy as np

arr = np.array([1,2,np.nan,4,np.nan,6])

print(np.isnan(arr))

"""
can we compare nan values ? = NO, we cannot compare it directly

"""



[False False  True False  True False]


'\ncan we compare nan values ? = NO, we cannot compare it directly\n\n'

In [53]:
# 2. nan_to_num, default - 0

import numpy as np

arr = np.array([1,2,np.nan,4,np.nan,6])

cleaned_arr = np.nan_to_num(arr, nan = 100)  # replace nan with 100, default - 0
print(cleaned_arr)
 

[  1.   2. 100.   4. 100.   6.]


In [54]:
# 3. infinite

# np.isinf(array) , eg: 10 ** 1000 or 1/0

import numpy as np

arr = np.array([1,2,np.inf, 4, -np.inf, 6])

print(np.isinf(arr))





[False False  True False  True False]


In [57]:
# replace
# np.isinf(array) , eg: 10 ** 1000 or 1/0

import numpy as np

arr = np.array([1,2,np.inf, 4, -np.inf, 6])

print(np.isinf(arr))

cleaned_arr = np.nan_to_num(arr, posinf = 1000, neginf = -1000)
print(cleaned_arr)

[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     6.]
